### ISSUE TITLE
error: %+vswan1invalid character

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#10]
For most people, these logs are quite annoying as they appear every 10 seconds. can we do anything about it?

```
time="2024-01-30 11:32:49.823" level=error msg="nodeName: %s, error: %+vswan1invalid character '.' looking for beginning of value" func=StatisticalSources file="k8s_service.go:347"
time="2024-01-30 11:32:59.822" level=error msg="nodeName: %s, error: %+vswan1invalid character '.' looking for beginning of value" func=StatisticalSources file="k8s_service.go:347"
time="2024-01-30 11:33:09.823" level=error msg="nodeName: %s, error: %+vswan1invalid character '.' looking for beginning of value" func=StatisticalSources file="k8s_service.go:347"
```

**Comment by sonic-chain** [comment]
Can you provide the log of the `kubectl logs --tail=1 -fn kube-system  resource-exporter-ds-xxxx` command?   `resource-exporter-ds-xxxx`  is the name of the pod.

**Comment by ThomasBlock** [comment]
Hmm i guess the problem is that resource-exproter runs on every node in the kubernetes cluster.. but the primary node might normally have no gpu, as it is intended to run compute-provider, give internet access etc..

So the resource-exproter is crashing:

```
kubectl get po -A
NAMESPACE                                       NAME                                                           READY   STATUS             RESTARTS        AGE
...
kube-system                                     resource-exporter-ds-fs5b5                                     1/1     Running            5 (27m ago)     5d
kube-system                                     resource-exporter-ds-mzgn7                                     0/1     CrashLoopBackOff   565 (13s ago)   47h
kube-system                                     resource-exporter-ds-whwkj                                     1/1     Running            92 (17h ago)    24h
```
```
ubectl logs -f -n kube-system resource-exporter-ds-mzgn7
./resource-exporter: symbol lookup error: ./resource-exporter: undefined symbol: nvmlErrorString
```

That brings me to another question: Are we allowed and is it possible, to run nodes inside the kubernetes cluster, which don't have gpu and have the only purpose of running CPU task? Could we just install some kind of "dummy gpu" ? or is it sufficient to install nivdia drivers, so just that the error disappears?

**Comment by sonic-chain** [comment]
The solution currently being fixed is that if the gpu information cannot be collected, just return empty and let it run normally. Other resource information is obtained from the k8s cluster.  After the repair is completed, you only need to update the resource-exporter component.

**Comment by ThomasBlock** [comment]
fixed in newest version
