### ISSUE TITLE
The error of collecting host hardware resource is still existed.

### ISSUE THREAD

**Issue by phoenixlhs** [swanchain/go-computing-provider#100]
computing-provider version : 0.5.1

CP Account Address(2.0):     0x0bb3b60AA174DFcc3daF78b46EcB4Edcb0a20894

node id : 
04e6ec185869d52d4998331eca6a2a705a93dd78ed617db67f4bc0299249c9d08ec86f5b4538aa828a0a130c2c6daf7ba3c7eb28ce431dc075dc4bffd37ab67380

errors on ubi task list : 
874766  0x5a01a....11D8e2f      CPU             fil-c2-512M                             failed  0.0000  2024-06-24 16:37:11
875560  0x38f02....95C2896      CPU             fil-c2-512M     0x2492a....fbea59f      success 0.0000  2024-06-24 17:07:33
876351  0x7E689....3E3360A      CPU             fil-c2-512M                             failed  0.0000  2024-06-24 17:37:11
![image](https://github.com/swanchain/go-computing-provider/assets/1990310/41411593-0256-4f82-b37c-a1854387c583)

content of error log: 
time="2024-06-24 16:37:11.982" level=error msg="collect host hardware resource failed, error: %+vinvalid character 'T' looking for beginning of value" func=checkResourceForUbi file="ubi.go:668"
time="2024-06-24 16:37:11.991" level=error msg="check resource failed, error: invalid character 'T' looking for beginning of value" func=DoUbiTaskForDocker file="ubi.go:532"
time="2024-06-24 17:37:11.892" level=error msg="collect host hardware resource failed, error: %+vinvalid character 'T' looking for beginning of value" func=checkResourceForUbi file="ubi.go:668"
time="2024-06-24 17:37:11.896" level=error msg="check resource failed, error: invalid character 'T' looking for beginning of value" func=DoUbiTaskForDocker file="ubi.go:532"
![image](https://github.com/swanchain/go-computing-provider/assets/1990310/ceba5eb5-76d0-4085-badf-44c8b64b0a80)

**Comment by Normalnoise** [comment]
You can ignore this error, it will restart automatically
