### ISSUE TITLE
rebooting

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#11]
I just wanted to ask what is the expected behaviour if i have to do maintenance  

1. how can i see which tasks / pods are running on which physical machine? and see how much cores etc are free?
2. when i reboot a machine, all the tasks are just canceled and deleted. is this expected behaviour?
3. how can i avoid Point 2? I can list all tasks with `computing-provider task list -v` and then kill every task with `computing-provider task delete`. is this oaky from a network perspective? will i get rewards ( partial until now) and my deposit back?

**Comment by Normalnoise** [comment]
> I just wanted to ask what is the expected behaviour if i have to do maintenance
> 
> 1. how can i see which tasks / pods are running on which physical machine? and see how much cores etc are free?
> 2. when i reboot a machine, all the tasks are just canceled and deleted. is this expected behaviour?
> 3. how can i avoid Point 2? I can list all tasks with `computing-provider task list -v` and then kill every task with `computing-provider task delete`. is this oaky from a network perspective? will i get rewards ( partial until now) and my deposit back?

1\  you can run `curl -k --location 'https://<YOUR_PUBLIC_IP>:<PORT>/api/v1/computing/cp'`

2\ yes, Orchestrator will monster your service, if the service is not available, the task will be terminated. 

3\ You must keep your server running, if the task is deleted, CP just can get a part of the total reward
