### ISSUE TITLE
Address and Reward History on Orchestrator Hub

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#12]
Hi. I just wanted to ask if the rewards are working as intended. Since over 48 hours i am successfully  receiving tasks. Thexy appear, run and disappear as intended.. other users can also start gpu tasks ans pay like 21 swan per hour,

```
computing-provider task list
TASK UUID    	TASK TYPE	WALLET ADDRESS	SPACE UUID   	SPACE NAME    	STATUS  
...e6c8e75c4e	CPU      	0x0A0...b2AB7 	...0b3e53ae80	063823012024  	Running	
...eec5f5dd84	CPU      	0x335...662e5 	...4af1f7a1b7	Mario         	Running	
...4a99df0f37	CPU      	0x3aa...1e8ED 	...f2f8e732a3	catty0481     	Running	
...2411c46948	CPU      	0x45B...97502 	...3e9a141683	kropes        	Running	
...53a72280db	CPU      	0x276...d6c82 	...5011a524b6	traidatngoc   	Running	
...4175204b63	CPU      	0x273...e40F3 	...7e1249bd88	Finder        	Running	
...74c456b3a2	CPU      	0x027...6C234 	...280dcb8cd3	minezweeperApp	Running	
...781ee34cb9	CPU      	0x217...020DA 	...8a078a5621	Jupyter-Labs  	Running	
...66bd5b18f7	CPU      	0x204...02eb7 	...287f69434c	traidatngoc46 	Running	
...23701c90be	CPU      	0xDBa...ad3a1 	...3c8a4307dc	GBanSKUY      	Running	
...cc13b550ed	CPU      	0x5C6...c7C1A 	...2aa2ca8ed3	Narkoboy      	Running	
...566d8fb305	CPU      	0xAe0...87304 	...32e4795f43	GameSwan      	Running	
...648b6424e7	CPU      	0x82D...b6e4a 	...ef3ba726f7	mihrahmine    	Running	
...63ddfe3f1b	CPU      	0x05E...d3C31 	...9435a5f8c7	SvoRa         	Running	
...3036ca4a22	CPU      	0x027...6C234 	...dce030b411	Newspace      	Running	
...4a2949c60b	CPU      	0x1Bf...8139b 	...a500e8256d	MusicGen      	Running	

```

but i don't get any onchain rewards. The `Collateral(SWAN-ETH)` is shrinking and shrinking. I see a "history" here https://orchestrator.swanchain.io/payment-history . but how does this tranform to an income?

![Bildschirmfoto vom 2024-01-31 09-03-37](https://github.com/swanchain/go-computing-provider/assets/43484940/3873b91d-c8c2-4a8e-aa5e-a30a0cec600d)

So i wanted to make sure that i understand the HUB correcntly. Is it correct that every provider has to fill out the google form first, and then can connect? I did this, but it looks like maybe there was an address error:
I have submitted two wallet addessses: 
`0xfe0...4981` is the hot wallet, computing-provider has the private key
`0x269E...22A9` is a cold wallet ( more to collect mainnet rewards at the end )

What i am doing is at the moment, is to set in the config
```
[HUB]
WalletAddress = `0x269E...22A9`
AccessToken = 'XXX"
```
So i can collect uptime stats, receive tasks and even receuve ubi tasks ( [with problems](https://github.com/swanchain/go-computing-provider/issues/9) ). But its strange, as compute-provider cannot sign anything or deposit collateral, as he does not have acces to the private key. So might this be a problem for collecting rewards?

What i can also do, is 
```
[HUB]
WalletAddress = `0xfe0...4981` 
AccessToken = 'YYY"
```
but then the compute-provider can not access the hub and tells me this error:
`level=warning msg="resp status: %d, retrying to connect to the Swan Hub server 404" func=sendHeartbeat file="initializer.go:41"`

last question regarding this: I did `computing-provider init `only with `--ownerAddress 0xfe0...4981`  and not `--beneficiaryAddress 0x269E...22A9`. Or should i do that?

maybe it would be the easiest way, if everything just runs on `0xfe0...4981` ?

**Comment by Normalnoise** [comment]
@ThomasBlock  thanks for your issues, we have noticed it.
firstly, in the `config.toml`
```
[HUB]
AccessToken = ""                                    # The Orchestrator's access token, Acquired from "https://orchestrator.swanchain.io" 
WalletAddress = ""                                  # The cp‘s wallet address
```
`AccessToken` should be acquired from "https://orchestrator.swanchain.io" > "show API-key", it will be used to connect to Orchestrator. it is not a wallet address

`WalletAddress` is the CP's wallet that will be used to add collateral snd receive the space reward

**Comment by Normalnoise** [comment]
> The Collateral(SWAN-ETH) is shrinking and shrinking

we have fixed this bug, in the testnet, the `Escrow` balance will be auto transferred to `Collateral` balance and reused as a collateral to deploy a space

**Comment by Normalnoise** [comment]
> last question regarding this: I did computing-provider init only with `--ownerAddress` 0xfe0...4981 and not --`beneficiaryAddress` 0x269E...22A9. Or should i do that?

> maybe it would be the easiest way, if everything just runs on 0xfe0...4981 ?

the beneficiaryAddress is a cold address for get reward. when you init the CP, you do not set the `--beneficiaryAddress`, the beneficiary address will be same with `ownerAddress`

**Comment by Andrew09if** [comment]
I have the same problem. 
I set "Benefeciary address" to my cold wallet. When I log in to Orchestrator dashboard wih my benefeciary wallet I see nothing in rewards history and UBI reward history tabs. 
When I log in to Orchestrator dashboard wih my owner hot wallet I see many pending rewards in reward history tab and no rewards in UBI history tab

![1](https://github.com/swanchain/go-computing-provider/assets/71209242/88539b01-8668-4755-b840-2d0f20ecb463)

**Comment by ThomasBlock** [comment]
> @ThomasBlock thanks for your issues, we have noticed it. firstly, in the `config.toml`
> 
> ```
> [HUB]
> AccessToken = ""                                    # The Orchestrator's access token, Acquired from "https://orchestrator.swanchain.io" 
> WalletAddress = ""                                  # The cp‘s wallet address
> ```
> 
> `AccessToken` should be acquired from "https://orchestrator.swanchain.io" > "show API-key", it will be used to connect to Orchestrator. it is not a wallet address
> 
> `WalletAddress` is the CP's wallet that will be used to add collateral snd receive the space reward

Thank you for the feedback. Yes that is how i also understood these two variables. You did not reply the other qeuestions:
a) is it okay to log in with a offline wallet?
b) why cant i login with the online wallet?

Here is how i tried it with the online wallet:
computing-provider wallet new
computing-provider wallet export 0xfe0...
take the private key and import it in metamask
send SWAN-ETH to the address
go to https://orchestrator.swanchain.io/ , login, deposit collateral, create api
enter WalletAddress and AccessToken in config.toml
see error 404

**Comment by Andrew09if** [comment]
The private key import scheme worked well for me. I can login to dashboard and no errors with API key in computing-provider.

**Comment by Normalnoise** [comment]
> a) is it okay to log in with a offline wallet?
You must log in the [dashboard](https://orchestrator.swanchain.io/) using `WalletAddress` in `config.toml`, to get the `AccessToken`(named API-key in dashboard), the wallet address and AccessToken must match, otherwise it will return 404. But the CP do not need the `WalletAddress` privateKey, you just config the wallet address in the config file

> b) why cant i login with the online wallet?

**Comment by Normalnoise** [comment]
> Are you sure that CP do not require private key for WalletAddress? How can you add collateral?

@Andrew09if you can add collateral in the https://orchestrator.swanchain.io/

**Comment by Normalnoise** [comment]
> I have the same problem. I set "Benefeciary address" to my cold wallet. When I log in to Orchestrator dashboard wih my benefeciary wallet I see nothing in rewards history and UBI reward history tabs. When I log in to Orchestrator dashboard wih my owner hot wallet I see many pending rewards in reward history tab and no rewards in UBI history tab
> 
> ![1](https://private-user-images.githubusercontent.com/71209242/301422247-88539b01-8668-4755-b840-2d0f20ecb463.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzcwMDUsIm5iZiI6MTcwNjc3NjcwNSwicGF0aCI6Ii83MTIwOTI0Mi8zMDE0MjIyNDctODg1MzliMDEtODY2OC00NzU1LWI4NDAtMmQwZjIwZWNiNDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4MzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NjE4ZTEyZmM4OWMyZjA0NjdlYTJmZDA1MDgzZTVhNDVkOGFlMmIwN2RiODNlM2U1ZDVkMTU1NzUxNmMwZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f92TunDtHSDNYAkyDbNJUiWpintm4a2cNzqpamV68iY)

@Andrew09if I have not see a success Ubi-task, after the Ubi-task become success, the reward will be sent two hours later.

you should check your ubi config, and test the process by this guideline: https://docs.swanchain.io/orchestrator/as-a-computing-provider/computing-provider-setup/faq#q-how-can-i-verify-if-my-computing-provider-is-set-up-to-receive-ubi-tasks

**Comment by ThomasBlock** [comment]
> > a) is it okay to log in with a offline wallet?
> 
> You must log in the [dashboard](https://orchestrator.swanchain.io/) using `WalletAddress` in `config.toml`, to get the `AccessToken`(named API-key in dashboard), the wallet address and AccessToken must match, otherwise it will return 404. But the CP do not need the `WalletAddress` privateKey, you just config the wallet address in the config file
> 
> > b) why cann't i login with the online wallet?
> 
> the online wallet and AccessToken must config in the config, if you see the 404, maybe you have another issue

Okay, i summarize that it is okay to have two separate wallets. And ubi rewards appear 2 hours later. But what about "normal" rewards, for tasks? when and on which address do they appear? ( on cp wallet or on HUB wallet ? )

**Comment by ThomasBlock** [comment]
Any updates on all the bugs?
- task payments still not processing
- i still can only connect with the "wrong"  offline wallet. i created new api key, but hub responds with this:

```
time="2024-02-03 09:18:47.159" level=error msg="report cluster node resources failed, status code: 403" func=reportClusterResource file="task_service.go:235"
time="2024-02-03 09:18:52.219" level=warning msg="resp status: %d, retrying to connect to the Swan Hub server 500" func=sendHeartbeat file="initializer.go:41"
time="2024-02-03 09:18:57.373" level=error msg="report cluster node resources failed, status code: 403" func=reportClusterResource file="task_service.go:235"
time="2024-02-03 09:19:06.831" level=warning msg="resp status: %d, retrying to connect to the Swan Hub server 500" func=sendHeartbeat file="initializer.go:41"
```

i also clrealy see in my logs that the private key is needed: 
```
time="2024-02-03 08:57:07.223" level=info msg="task_id: 14, C2 proof out received: {TaskId:14 TaskType:1 Proof:tBK+ehg/ryLH4LfUpd46C2fWoirG69CnDt67vjdkbAKIgD/Q9kkpfysTsx7shbGbjj20ay7fhXINgg6PZNZz55RAeFr1wT+kLSpVGII+tQuSY5c3GoinrVDv0SiELvopFCa/n3jLTEqXMceimV6+Rdf0LmEPJncweO/PMM4ZVvzXXCXJzgLTvp82IyLFd+hmo2XlK7twh8IxzZN6F0w71GEywSaGxLOez3Hq0piHUe7kb/GRFIVSwD3p5yiFRK4V ZkType:fil-c2-512M NameSpace:ubi-task-14}" func=ReceiveUbiProof file="cp_service.go:855"
time="2024-02-03 08:57:07.248" level=error msg="the address: 0x269E..., private key key info not found," func=ReceiveUbiProof file="cp_service.go:871"
```

so can you again point out: is there any manual whitelisting involved in the hub? could you please allow my second wallet address?

**Comment by sonic-chain** [comment]
1. Delete [HUB].AccessToken in config.toml, use [HUB].WalletAddress to regenerate AccessToken on the HUB website, and then reconfigure it

**Comment by sonic-chain** [comment]
2. If the first solution does not work, you can delete private_key under CP_PATH, repeat the operation of the first solution to start cp, and then execute the `computing-provider init ` command

**Comment by ThomasBlock** [comment]
fixed in newest version
