### ISSUE TITLE
Transaction costs

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#127]
How do SWAN network fees work?
( how does the SWAN blockchain work in general - can we join as a evm blockchain node? )

On Ethereum Mainnet, fees are astronomical right now.
So this also relates to Swan Mainnet fees?

A friend just wanted to register a ECP node. It is barely possible as it would costs like 12 Dollars..
can we do anything or do we have to wait?
can we extend the ECP Early Participant Reward period by some days?

```
computing-provider account create ...
Error: deploy cp account contract failed, error: insufficient funds for gas * price + value: balance 5000000000000000, tx cost 5108109113711028, overshot 108109113711028
```

**Comment by Normalnoise** [comment]
this browser can not show the gas, if you want to know the all tx fee, you can see this page: https://mainnet-explorer.swanchain.io/address/0x82AB7Bd300976fe5e294586aD491d6bBd1CAfb06?tab=coin_balance_history

**Comment by ThomasBlock** [comment]
> this browser can not show the gas, if you want to know the all tx fee, you can see this page: https://mainnet-explorer.swanchain.io/address/0x82AB7Bd300976fe5e294586aD491d6bBd1CAfb06?tab=coin_balance_history

okay that confirmes that 0.00089455 are deducted. still roughly 3 Dollars. This seems really high for a layer2. can you explain that?

**Comment by Normalnoise** [comment]
I think it has been solved, please confirm it @ThomasBlock
