### ISSUE TITLE
doubi ubi-task all failed

### ISSUE THREAD

**Issue by scvpark** [swanchain/go-computing-provider#19]
I have completed a lot of ubi-tasks. However, i have check failed ubi-tasks from today.
All failed tasks include a DoUbiTask function.

**computing-provider version**
computing-provider version 0.4.2+git.24931a7

**computing-provider ubi-task list**
3027   	CPU      	fil-c2-512M	0xff883d04b04292bf	success	10.00 	2024-02-04 16:00:38
3045   	CPU      	fil-c2-512M	0x05c00b8cfe463b12	success	10.00 	2024-02-04 16:30:38
3061   	CPU      	fil-c2-512M	0x163d0685480ab17       success	10.00 	2024-02-04 17:00:43
3078   	CPU      	fil-c2-512M	0xdb894c594515c97	success	10.00 	2024-02-04 17:30:39
3094   	CPU      	fil-c2-512M	0x05c001997dfbfea  	success	10.00 	2024-02-04 18:00:36
3113   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 18:30:41
3129   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 19:00:50
3145   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 19:30:42
3163   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 20:00:41
3181   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 20:30:51
3199   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 21:00:40
3217   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 21:30:44
3236   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 22:00:42
3255   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 22:30:44
3274   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 23:00:41
3293   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-04 23:30:49
3312   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 00:00:48
3331   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 00:30:42
3350   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 01:00:42
3369   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 01:30:46
3388   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 02:00:40
3407   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 02:30:41
3426   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 03:00:39
3445   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 03:30:42
3464   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 04:00:40
3483   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 04:30:40
3502   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 05:00:51
3520   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 05:30:41
3538   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 06:00:45
3555   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 06:30:48
3572   	CPU      	fil-c2-512M	                                                                  	failed 	0.0   	2024-02-05 07:00:41

**cat cp.log  | grep 3572**
time="2024-02-05 07:00:41.516" level=info msg="receive ubi task received: {ID:3572 Name:1000-0-8-1968 Type:1 ZkType:fil-c2-512M InputParam:https://286cb2c989.acl.multichain.storage/ipfs/QmU8XLHUSUeppBHG7qRRRBzz9LK556bMJiqfyQuFognrAL Signature:0x4497a0598adbfdac12336f7a904c00ac7f618fd8f39130b5037aefd0ea50dc9b139e1e431cbe61c22a071e60001a19aea0c47d4026a7d1d5b7f17820c18dc05401 Resource:0xc000892c00}" func=DoUbiTask file="cp_service.go:547"
time="2024-02-05 07:00:41.516" level=info msg="ubi task sign verifing, task_id: 3572, type: fil-c2-512M, verify: true" func=DoUbiTask file="cp_service.go:587"

**Comment by Normalnoise** [comment]
can you provide your ubi container error log?

**Comment by scvpark** [comment]
Which of the docker containers is a ubi container??

**Comment by Normalnoise** [comment]
it should be like this 
<img width="501" alt="image" src="https://github.com/swanchain/go-computing-provider/assets/102578774/5800f585-6de1-43d1-89c7-92b4dc87572d">

**Comment by zsp03** [comment]
> it should be like this <img alt="image" width="501" src="https://private-user-images.githubusercontent.com/102578774/302720760-5800f585-6de1-43d1-89c7-92b4dc87572d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzY2NzIsIm5iZiI6MTcwNzI3NjM3MiwicGF0aCI6Ii8xMDI1Nzg3NzQvMzAyNzIwNzYwLTU4MDBmNTg1LTZkZTEtNDNkMS04OWM3LTkyYjRkYzg3NTcyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwMzI2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGI5MzBjMDBkOTRhMmFjYjczNzE2ODE1OWRjNTMzNTRlNGZlZTk5Y2Y4ZDlmNzI3MWM3OGEyZmYyNmU1NGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uFaOZmNYHSyCGG34LA66YaLAT7XS49tY9VVi37UwXhk">

I have the same issue, however i cannot view the logs because it gets deleted too fast (BackOffLimit)
I tried finding solution but it all seems to be a setting in the yaml file which only the developer can change.

I can however view the event logs and as you can see it only takes 3s to reach the limit. And yes now the cpu is correctly detected but still cannot figure out whats wrong with the pods.

![image](https://github.com/swanchain/go-computing-provider/assets/112597617/4c9cd190-a7e1-4e83-9f59-ef7e4828ca6e)

**Comment by scvpark** [comment]
The ubi-task pod disappears too quickly to check the log.
Is there a way to check the logs differently?
I checked with the computing-providerubi-task list --show-failed command, and about 60% of the tasks fail per day.

**Comment by Normalnoise** [comment]
please upgrade to v0.5.1
