### ISSUE TITLE
additional gpu types

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#24]
@ThomasBlock UBI task will use all kinds of GPU, if you have a gpu type that is not in the hardware list, please publish a new issue, we are glad to add it to the list.

_Originally posted by @Normalnoise in https://github.com/swanchain/go-computing-provider/issues/18#issuecomment-1923520161_
            
here i list my furrther gpus which are not included in the lagrange sapce deployment screen:
RTX 4060 TI
RTX 4070
RTX 4080
A2000
A5000

**Comment by Normalnoise** [comment]
Ok we will add them to our list next version.  It will happen After two weeks
