### ISSUE TITLE
Reward History. Claim Reward: Cannot get task contract

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#25]
since two weeks i have a lot of tasks running succesfully.
how can we claim the rewards for that?

on the page `https://orchestrator.swanchain.io/payment-history` there is a button `claim reward`, but it does not work:

![Bildschirmfoto vom 2024-02-11 08-58-52](https://github.com/shamirlabs/diva-alpha-net/assets/43484940/4a16306e-f913-4610-9995-14b5314efa8d)

**Comment by Normalnoise** [comment]
@ThomasBlock thanks for your issue, we are fixing the issue in the devnet, once it is online, we will have a announcement

**Comment by ThomasBlock** [comment]
in case somebody is interested: rewards still broken. i have not a single success

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/c6f2598a-32e4-461d-8f59-baa086e9d849)
