### ISSUE TITLE
network waekness: free spam tasks for everyone filling the provider

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#28]
@Normalnoise i am really not satisfied with your communication. you ignore my points time and time again and just answer to one specific topic. here is my problem for the last two days:

we see high usage and low deployments. My node is spammed with worthless cpu tasks. i cant do ubi and i can not lease my gpu

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/97dfc5cf-3fc1-4fa4-98b9-76b9020466d3)

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/3b4f807a-4829-490e-977f-bdc147e93eee)

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/d29ee507-50d4-40cc-bd72-ac72d4bdec32)

on the other hand we have very little paying tasks:

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/7417c9cc-6c23-4705-8bc2-ed4af358fefa)

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/9deb4aa9-d024-43bb-9bfc-8896de75a73b)

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/b2445c1d-9f8f-435d-8664-617e43a58372)

That does not add up! How can the network have 144 deployments, when i alone have 110?

I think i know the reason for this. anybody can create a task for every provider. without using lagrange and without paying for it! there is no security built in. i did this on my own node:

```
curl --location --request POST 'https://domain:com:1234/api/v1/computing/lagrange/jobs' \
--header 'Content-Type: application/json' \
--data-raw '{
"uuid": "5641877b-dc94-469a-bb3b-ecab6d10f7dd",
"name": "Job-5641877b-dc94-469a-bb3b-ecab6d10f7dd",
"status": "Submitted",
"duration": 900,
"job_source_uri": "https://api.lagrangedao.org/spaces/51d6abbb-f928-43e4-91fd-79e93e2b276f",
"storage_source": "lagrange",
"task_uuid": "92cd5595-9789-4af3-9100-7c7e4aacb456"
}'
```

```
time="2024-01-28 09:48:41.908" level=info msg="checkResourceAvailableForSpace: needCpu: 2, needMemory: 16.00, needStorage: 30.00" func=checkResourceAvailableForSpace file="cp_service.go:1199"
time="2024-01-28 09:48:41.908" level=info msg="checkResourceAvailableForSpace: remainderCpu: 2, remainderMemory: 18.00, remainderStorage: 353.00" func=checkResourceAvailableForSpace file="cp_service.go:1200"
time="2024-01-28 09:48:41.908" level=info msg="checkResourceAvailableForSpace: needCpu: 2, needMemory: 16.00, needStorage: 30.00" func=checkResourceAvailableForSpace file="cp_service.go:1199"
time="2024-01-28 09:48:41.908" level=info msg="checkResourceAvailableForSpace: remainderCpu: 23, remainderMemory: 19.00, remainderStorage: 1593.00" func=checkResourceAvailableForSpace file="cp_service.go:1200"
time="2024-01-28 09:48:41.908" level=info msg="submitting job..." func=submitJob file="cp_service.go:123"
time="2024-01-28 09:48:42.063" level=info msg="uuid: 51d6abbb-f928-43e4-91fd-79e93e2b276f, spaceName: Minesweeper, hardwareName: CPU only · 2 vCPU · 16 GiB" func=DeploySpaceTask file="cp_service.go:1008"
```
You just need to create a space, a random uuid and know the domain of the provider

my questions:
1. can you confirm this network weakness?
2. can you list the official IP addresses lagrange is calling from so that we can whitelist our firewall ?
3. can you please further implement a way that we can only lease GPU tasks, so that CPU tasls will not fill up the host

**Comment by ThomasBlock** [comment]
Hm on the other hand i see in the logs that the taks come from the IP address as usual:

```
[GIN] 2024/02/27 - 15:19:32 | 200 |  4.601679644s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:19:50 | 200 |   4.52719555s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:23:22 | 200 |  5.024531152s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:23:38 | 200 |  4.628892992s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:23:50 | 200 |   4.53017102s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:24:54 | 200 |  4.561304821s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:26:13 | 200 |  4.676522118s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:26:49 | 200 |  4.427365092s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:27:38 | 200 |  4.435639228s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
[GIN] 2024/02/27 - 15:27:53 | 200 |   4.47142667s |   38.104.153.43 | POST     "/api/v1/computing/lagrange/jobs"
```

**Comment by Normalnoise** [comment]
and we have designed CP can just get the task from swan Orchestrator. it will be next version

**Comment by Normalnoise** [comment]
@ThomasBlock thanks for your feedback, we have a fix branch to help you clear the spam tasks, please use this branch to build a new version `fix-a100`

**Comment by Normalnoise** [comment]
#38 has fixed this bug
