### ISSUE TITLE
update getLocalIPAddress

### ISSUE THREAD

**Issue by dr4mohamed** [swanchain/go-computing-provider#52]
https://ipapi.co/ip start using  Verifying you are human. This may take a few seconds. 
logs : 
`
time="2024-04-28 09:32:23.572" level=info msg="publicIpAddress: <!DOCTYPE html><html lang=\"en-US\"><head><title>Just a moment...</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"><meta name=\"robots\" content=\"noi
`
use https://ifconfig.me/ with User-Agent: curl/7.61.1

**Comment by Normalnoise** [comment]
we need regional information, not just public IP

**Comment by Normalnoise** [comment]
I have tested `https://ipapi.co/ip`, it works

**Comment by dr4mohamed** [comment]
use in same region only not all regions, work in my vps , and not working with my home network

**Comment by Normalnoise** [comment]
curl ipinfo.io

it seems this more friendly

**Comment by Normalnoise** [comment]
https://github.com/swanchain/go-computing-provider/pull/54

**Comment by dr4mohamed** [comment]
use : http://ip-api.com/json/ without ip to get the ip and metadata in the same request

**Comment by Normalnoise** [comment]
thanks for your feedback, we will improve it
