### ISSUE TITLE
Unable to POST the final job completion result

### ISSUE THREAD

**Issue by aa66609** [swanchain/go-computing-provider#59]
![image](https://github.com/swanchain/go-computing-provider/assets/13633514/807c897e-b0af-4a5f-b3ad-5c8fbf91ab86)
level=error msg="Failed send a request, error: Post "http://172.23.23.XX:9085/api/v1/computing/cp/docker/receive/ubi": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" func=func4 file="main.go:633"

 WARN    ubi-bench       ubi-bench/main.go:113   Post "http://172.23.23.XX:9085/api/v1/computing/cp/docker/receive/ubi": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

![image](https://github.com/swanchain/go-computing-provider/assets/13633514/13fcb890-8fdf-4d90-aa34-c4fe5143fa9d)
 I found that in the log, there is no reception of the api: api/v1/computing/cp/docker/receive/ubi   (POST)

I use frp server as my swan public ip (34.80.XX.XX:9085) , and the local machine is frp client to connect. The public ip (34.80.XX.XX:9085) is used to receive jobs and heartbeat checks, but after the job is completed, the api of the final reporting job is /v1/computing/cp/docker/receive/ubi (POST) uses my client’s IP (172.23.23.XX:9085), causing timeout

For the final reporting job's completed, need to use the config MultiAddress = "/ip4/34.80.XX.X/tcp/9085" (34.80.XX.XX:9085)  to POST the api: /v1/computing/cp/docker/receive/ubi 
Otherwise, I ran all day, took many jobs and completed them, but in the end none of them reported success.

**Comment by sonic-chain** [comment]
Submit the proof using the public IP address, modify the branch reference https://github.com/swanchain/go-computing-provider/tree/fix-localip-timeout, pull the branch code, compile the cp binary and replace it.

**Comment by aa66609** [comment]
> Submit the proof using the public IP address, modify the branch reference https://github.com/swanchain/go-computing-provider/tree/fix-localip-timeout, pull the branch code, compile the cp binary and replace it.

Is it possible to directly clone the branch and compile and execute it?
Are there any additional changes that need to be made?

**Comment by aa66609** [comment]
`/*
		localIp, err := getLocalIp()
		if err != nil {
			logs.GetLogger().Errorf("check resource failed, error: %v", err)
			return
		}

		receiveUrl := fmt.Sprintf("http://%s:%d/api/v1/computing/cp/docker/receive/ubi", localIp, conf.GetConfig().API.Port)
		*/
		
		multiAddressSplit := strings.Split(conf.GetConfig().API.MultiAddress, "/")
		receiveUrl := fmt.Sprintf("http://%s:%s/api/v1/computing/cp/docker/receive/ubi", multiAddressSplit[2], multiAddressSplit[4])`

**Comment by sonic-chain** [comment]
I also used public IP to solve this problem. Thank you for your reply.
