### ISSUE TITLE
fil-c2.env note suggestions in FCP deployment documentation

### ISSUE THREAD

**Issue by aa66609** [swanchain/go-computing-provider#62]
Today, when I deployed fcp on a machine without a GPU, I deployed it according to the documentation, but in the end the ubi task pod could not start normally. Later I found that the environment variables in fil-c2.env needed to be changed.

Since the deployed machine does not have a GPU, fil-c2.env needs to add BELLMAN_NO_GPU=1 instead of using the RUST_GPU_TOOLS_CUSTOM_GPU

**Comment by Normalnoise** [comment]
Thanks for your feedback. We have fixed the issue in the `releases` branch, When you receive a CPU task, the `BELLMAN_NO_GPU=1` will be set in the fil-c2 task.
