### ISSUE TITLE
How to collect previous profits

### ISSUE THREAD

**Issue by hash889900** [swanchain/go-computing-provider#94]
I have created multiple wallet running tasks, all of which are independently opened. Now, I want to know how to transfer out the income from the wallet

**Comment by Normalnoise** [comment]
FCP or ECP？

**Comment by hash889900** [comment]
> FCP or ECP？

ecp  I would like to know how to collect profits through commands, which will facilitate my batch operations

**Comment by Normalnoise** [comment]
computing-provider ubi list --show-failed --verbose

**Comment by hash889900** [comment]
> computing-provider ubi list --show-failed --verbose

https://github.com/swanchain/go-computing-provider/issues/94#issuecomment-2175397831
What I want is to use commands to transfer profits to another wallet

**Comment by hash889900** [comment]
@Normalnoise

**Comment by Normalnoise** [comment]
your all profit will be sent to beneficiary address, if you want to collect profits, you only need to changeBeneficiaryAddress  to same address
