### ISSUE TITLE
ThomasBlock ThomasBlock-ECP no more ECP jobs, wrong free RAM

### ISSUE THREAD

**Issue by ThomasBlock** [swanchain/go-computing-provider#95]
1. since 48 hours there are no more ECP jobs. one reason could be that ECP only reports 6 GB RAM of 32 GB. I have no other software running. what can i fo?
2. The Jobs i got last week are only 512 M GPU. How can i get 32G Jobs -  are there special hardware requirements? What about Aleo?

```
/usr/local/bin/computing-provider -v
computing-provider version 0.5.1+git.a47e4a3

CP Account Info:           	                                                                                                                                   
   CP Account Address(2.0):	0xC39230f372Db8ABc2f2bA13d23B8206afB2b1ECC                                                                                        	
   Name:                   	ThomasBlock-ECP                                                                                                                   	
   Owner:                  	0xaC43f4ed670daaaB06391ffa0FDe48407972B4BD                                                                                        	
   Node ID:                	04d03fc936bdb1f0f879b3d2b77bbe783d258090ccd4ce7ed2bc36bdeb7677c0602e1e0de5aa7d671e972871d4957518fe1656c0f1466c8f41ffa8505892c881d5

Capabilities:              	
   Task Types:             	Fil-C2-512M,Aleo,Fil-C2-32G        
```

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/63b58ae8-8620-4e1a-bd32-2067a00b386f)

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/324cdebb-38d2-4db4-b2d5-d95f7bd13bd2)

![Bildschirmfoto vom 2024-06-17 10-43-17](https://github.com/swanchain/go-computing-provider/assets/43484940/a544d698-ee22-45c3-8671-20c3d182b675)

**Comment by ThomasBlock** [comment]
update: it fixed itself.. ?

```
time="2024-06-17 10:51:04.277" level=info msg="collect hardware resource, freeCpu:24, freeMemory: 6 GiB, freeStorage: 226 GiB, freeGpu: map[NVIDIA 4070 SUPER:1]" func=reportClusterResourceForDocker file="ubi.go:952"
time="2024-06-17 10:57:04.278" level=info msg="collect hardware resource, freeCpu:24, freeMemory: 31.63 GiB, freeStorage: 226.51 GiB, freeGpu: map[NVIDIA 4070 SUPER:1]" func=reportClusterResourceForDocker file="ubi.go:952"
```

**Comment by sonic-chain** [comment]
> update: it fixed itself.. ?
> 
> ```
> time="2024-06-17 10:51:04.277" level=info msg="collect hardware resource, freeCpu:24, freeMemory: 6 GiB, freeStorage: 226 GiB, freeGpu: map[NVIDIA 4070 SUPER:1]" func=reportClusterResourceForDocker file="ubi.go:952"
> time="2024-06-17 10:57:04.278" level=info msg="collect hardware resource, freeCpu:24, freeMemory: 31.63 GiB, freeStorage: 226.51 GiB, freeGpu: map[NVIDIA 4070 SUPER:1]" func=reportClusterResourceForDocker file="ubi.go:952"
> ```



> update: it fixed itself.. ?
> 
> ```
> time="2024-06-17 10:51:04.277" level=info msg="collect hardware resource, freeCpu:24, freeMemory: 6 GiB, freeStorage: 226 GiB, freeGpu: map[NVIDIA 4070 SUPER:1]" func=reportClusterResourceForDocker file="ubi.go:952"
> time="2024-06-17 10:57:04.278" level=info msg="collect hardware resource, freeCpu:24, freeMemory: 31.63 GiB, freeStorage: 226.51 GiB, freeGpu: map[NVIDIA 4070 SUPER:1]" func=reportClusterResourceForDocker file="ubi.go:952"
> ```

The bug of resource acquisition has been fixed

**Comment by ThomasBlock** [comment]
ok thank you. i can confirm that jobs are working now

![image](https://github.com/swanchain/go-computing-provider/assets/43484940/93ed56b9-070a-4b11-b00d-d84982bf087d)
