### ISSUE TITLE
cron task bug :delete space task error

### ISSUE THREAD

**Issue by harleyLuke** [swanchain/go-computing-provider#97]
The screenshots are very clear, no explanation is needed
![image](https://github.com/swanchain/go-computing-provider/assets/117342269/353f8842-1e5b-4ac6-94f7-b3e2a4d95bd8)

**Comment by Normalnoise** [comment]
it has been fixed, please use branch `fix-doc` https://github.com/swanchain/go-computing-provider/tree/fix-doc/ubi
